# Generated by Django 3.0.3 on 2020-05-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_auto_20200503_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ca',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
