# Generated by Django 3.0.3 on 2020-05-02 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_mentee'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='ans',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentee',
            name='ques',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentee',
            name='phn_num',
            field=models.IntegerField(unique=True),
        ),
    ]
