# Generated by Django 3.0.3 on 2020-05-03 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_auto_20200503_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('ques', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Quiz.Question')),
                ('ans', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='mentee',
            name='ques',
        ),
        migrations.AlterField(
            model_name='mentee',
            name='ans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Answer'),
        ),
    ]
