# Generated by Django 3.0.3 on 2020-05-03 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_auto_20200503_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='ans',
        ),
        migrations.AddField(
            model_name='question',
            name='ans',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.Mentee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentee',
            name='batch_num',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mentee',
            name='phn_num',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
