# Generated by Django 3.0.3 on 2020-05-03 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_auto_20200503_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ans',
            new_name='c_ans',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ans',
            new_name='name',
        ),
        migrations.AddField(
            model_name='answer',
            name='id',
            field=models.AutoField(auto_created=True, default=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='ques',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Question'),
        ),
    ]
