# Generated by Django 3.0.3 on 2020-05-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_auto_20200503_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
    ]
