# Generated by Django 3.0.3 on 2020-05-03 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_remove_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.Mentee'),
        ),
    ]
