# Generated by Django 3.0.3 on 2020-05-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0012_auto_20200503_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.ManyToManyField(null=True, to='Quiz.Mentee'),
        ),
    ]
