# Generated by Django 3.0.3 on 2020-05-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0013_question_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
    ]
