# Generated by Django 3.0.3 on 2020-05-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0014_remove_question_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(default=1, max_length=1, primary_key=True, serialize=False),
        ),
    ]
