# Generated by Django 3.0.3 on 2020-05-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0015_auto_20200503_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='ans1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentee',
            name='ans2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentee',
            name='ans3',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentee',
            name='ans4',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentee',
            name='ans5',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
