# Generated by Django 3.0.3 on 2020-05-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0016_auto_20200503_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
