# Generated by Django 3.0.3 on 2020-05-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0017_mentee_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
