# Generated by Django 3.0.3 on 2020-05-03 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0018_mentee_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
