# Generated by Django 3.0.3 on 2020-05-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0019_auto_20200503_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(default=1, max_length=2, primary_key=True, serialize=False),
        ),
    ]
